// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/firestore/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if canImport(FoundationEssentials)
package import FoundationEssentials
#else
package import Foundation
#endif
package import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A set of field paths on a document.
/// Used to restrict a get or update operation on a document to a subset of its
/// fields.
/// This is different from standard field masks, as this is always scoped to a
/// [Document][google.firestore.v1.Document], and takes in account the dynamic
/// nature of [Value][google.firestore.v1.Value].
package nonisolated struct Google_Firestore_V1_DocumentMask: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The list of field paths in the mask. See
  /// [Document.fields][google.firestore.v1.Document.fields] for a field path
  /// syntax reference.
  package var fieldPaths: [String] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// A precondition on a document, used for conditional operations.
package nonisolated struct Google_Firestore_V1_Precondition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The type of precondition.
  package var conditionType: Google_Firestore_V1_Precondition.OneOf_ConditionType? = nil

  /// When set to `true`, the target document must exist.
  /// When set to `false`, the target document must not exist.
  package var exists: Bool {
    get {
      if case .exists(let v)? = conditionType {return v}
      return false
    }
    set {conditionType = .exists(newValue)}
  }

  /// When set, the target document must exist and have been last updated at
  /// that time. Timestamp must be microsecond aligned.
  package var updateTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {
      if case .updateTime(let v)? = conditionType {return v}
      return SwiftProtobuf.Google_Protobuf_Timestamp()
    }
    set {conditionType = .updateTime(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The type of precondition.
  package nonisolated enum OneOf_ConditionType: Equatable, Sendable {
    /// When set to `true`, the target document must exist.
    /// When set to `false`, the target document must not exist.
    case exists(Bool)
    /// When set, the target document must exist and have been last updated at
    /// that time. Timestamp must be microsecond aligned.
    case updateTime(SwiftProtobuf.Google_Protobuf_Timestamp)

  }

  package init() {}
}

/// Options for creating a new transaction.
package nonisolated struct Google_Firestore_V1_TransactionOptions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The mode of the transaction.
  package var mode: Google_Firestore_V1_TransactionOptions.OneOf_Mode? = nil

  /// The transaction can only be used for read operations.
  package var readOnly: Google_Firestore_V1_TransactionOptions.ReadOnly {
    get {
      if case .readOnly(let v)? = mode {return v}
      return Google_Firestore_V1_TransactionOptions.ReadOnly()
    }
    set {mode = .readOnly(newValue)}
  }

  /// The transaction can be used for both read and write operations.
  package var readWrite: Google_Firestore_V1_TransactionOptions.ReadWrite {
    get {
      if case .readWrite(let v)? = mode {return v}
      return Google_Firestore_V1_TransactionOptions.ReadWrite()
    }
    set {mode = .readWrite(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The mode of the transaction.
  package nonisolated enum OneOf_Mode: Equatable, Sendable {
    /// The transaction can only be used for read operations.
    case readOnly(Google_Firestore_V1_TransactionOptions.ReadOnly)
    /// The transaction can be used for both read and write operations.
    case readWrite(Google_Firestore_V1_TransactionOptions.ReadWrite)

  }

  /// The type of concurrency control mode for transactions.
  package nonisolated enum ConcurrencyMode: SwiftProtobuf.Enum, Swift.CaseIterable {
    package typealias RawValue = Int

    /// Start the transaction with the database-level default concurrency mode.
    case unspecified // = 0

    /// Use optimistic concurrency control for the new transaction.
    case optimistic // = 1

    /// Use pessimistic concurrency control for the new transaction.
    case pessimistic // = 2
    case UNRECOGNIZED(Int)

    package init() {
      self = .unspecified
    }

    package init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .optimistic
      case 2: self = .pessimistic
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    package var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .optimistic: return 1
      case .pessimistic: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    package static let allCases: [Google_Firestore_V1_TransactionOptions.ConcurrencyMode] = [
      .unspecified,
      .optimistic,
      .pessimistic,
    ]

  }

  /// Options for a transaction that can be used to read and write documents.
  package nonisolated struct ReadWrite: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// An optional transaction to retry.
    package var retryTransaction: Data = Data()

    /// Optional. The concurrency control mode to use for this transaction.
    ///
    /// A database is able to use different concurrency modes for different
    /// transactions simultaneously.
    ///
    /// 3rd party auth requests are only allowed to create optimistic
    /// read-write transactions and must specify that here even if the
    /// database-level setting is already configured to optimistic.
    package var concurrencyMode: Google_Firestore_V1_TransactionOptions.ConcurrencyMode = .unspecified

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}
  }

  /// Options for a transaction that can only be used to read documents.
  package nonisolated struct ReadOnly: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The consistency mode for this transaction. If not set, defaults to strong
    /// consistency.
    package var consistencySelector: Google_Firestore_V1_TransactionOptions.ReadOnly.OneOf_ConsistencySelector? = nil

    /// Reads documents at the given time.
    ///
    /// This must be a microsecond precision timestamp within the past one
    /// hour, or if Point-in-Time Recovery is enabled, can additionally be a
    /// whole minute timestamp within the past 7 days.
    package var readTime: SwiftProtobuf.Google_Protobuf_Timestamp {
      get {
        if case .readTime(let v)? = consistencySelector {return v}
        return SwiftProtobuf.Google_Protobuf_Timestamp()
      }
      set {consistencySelector = .readTime(newValue)}
    }

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    /// The consistency mode for this transaction. If not set, defaults to strong
    /// consistency.
    package nonisolated enum OneOf_ConsistencySelector: Equatable, Sendable {
      /// Reads documents at the given time.
      ///
      /// This must be a microsecond precision timestamp within the past one
      /// hour, or if Point-in-Time Recovery is enabled, can additionally be a
      /// whole minute timestamp within the past 7 days.
      case readTime(SwiftProtobuf.Google_Protobuf_Timestamp)

    }

    package init() {}
  }

  package init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "google.firestore.v1"

nonisolated extension Google_Firestore_V1_DocumentMask: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".DocumentMask"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}field_paths\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.fieldPaths) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fieldPaths.isEmpty {
      try visitor.visitRepeatedStringField(value: self.fieldPaths, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_DocumentMask, rhs: Google_Firestore_V1_DocumentMask) -> Bool {
    if lhs.fieldPaths != rhs.fieldPaths {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_Precondition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Precondition"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}exists\0\u{3}update_time\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.conditionType != nil {try decoder.handleConflictingOneOf()}
          self.conditionType = .exists(v)
        }
      }()
      case 2: try {
        var v: SwiftProtobuf.Google_Protobuf_Timestamp?
        var hadOneofValue = false
        if let current = self.conditionType {
          hadOneofValue = true
          if case .updateTime(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.conditionType = .updateTime(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.conditionType {
    case .exists?: try {
      guard case .exists(let v)? = self.conditionType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .updateTime?: try {
      guard case .updateTime(let v)? = self.conditionType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_Precondition, rhs: Google_Firestore_V1_Precondition) -> Bool {
    if lhs.conditionType != rhs.conditionType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_TransactionOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".TransactionOptions"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}read_only\0\u{3}read_write\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try {
        var v: Google_Firestore_V1_TransactionOptions.ReadOnly?
        var hadOneofValue = false
        if let current = self.mode {
          hadOneofValue = true
          if case .readOnly(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.mode = .readOnly(v)
        }
      }()
      case 3: try {
        var v: Google_Firestore_V1_TransactionOptions.ReadWrite?
        var hadOneofValue = false
        if let current = self.mode {
          hadOneofValue = true
          if case .readWrite(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.mode = .readWrite(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.mode {
    case .readOnly?: try {
      guard case .readOnly(let v)? = self.mode else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .readWrite?: try {
      guard case .readWrite(let v)? = self.mode else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_TransactionOptions, rhs: Google_Firestore_V1_TransactionOptions) -> Bool {
    if lhs.mode != rhs.mode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_TransactionOptions.ConcurrencyMode: SwiftProtobuf._ProtoNameProviding {
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0CONCURRENCY_MODE_UNSPECIFIED\0\u{1}OPTIMISTIC\0\u{1}PESSIMISTIC\0")
}

nonisolated extension Google_Firestore_V1_TransactionOptions.ReadWrite: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Google_Firestore_V1_TransactionOptions.protoMessageName + ".ReadWrite"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}retry_transaction\0\u{3}concurrency_mode\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.retryTransaction) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.concurrencyMode) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.retryTransaction.isEmpty {
      try visitor.visitSingularBytesField(value: self.retryTransaction, fieldNumber: 1)
    }
    if self.concurrencyMode != .unspecified {
      try visitor.visitSingularEnumField(value: self.concurrencyMode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_TransactionOptions.ReadWrite, rhs: Google_Firestore_V1_TransactionOptions.ReadWrite) -> Bool {
    if lhs.retryTransaction != rhs.retryTransaction {return false}
    if lhs.concurrencyMode != rhs.concurrencyMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_TransactionOptions.ReadOnly: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Google_Firestore_V1_TransactionOptions.protoMessageName + ".ReadOnly"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}read_time\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try {
        var v: SwiftProtobuf.Google_Protobuf_Timestamp?
        var hadOneofValue = false
        if let current = self.consistencySelector {
          hadOneofValue = true
          if case .readTime(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.consistencySelector = .readTime(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .readTime(let v)? = self.consistencySelector {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_TransactionOptions.ReadOnly, rhs: Google_Firestore_V1_TransactionOptions.ReadOnly) -> Bool {
    if lhs.consistencySelector != rhs.consistencySelector {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
