// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/firestore/v1/document.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if canImport(FoundationEssentials)
package import FoundationEssentials
#else
package import Foundation
#endif
package import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A Firestore document.
///
/// Must not exceed 1 MiB - 4 bytes.
package nonisolated struct Google_Firestore_V1_Document: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The resource name of the document, for example
  /// `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
  package var name: String = String()

  /// The document's fields.
  ///
  /// The map keys represent field names.
  ///
  /// Field names matching the regular expression `__.*__` are reserved. Reserved
  /// field names are forbidden except in certain documented contexts. The field
  /// names, represented as UTF-8, must not exceed 1,500 bytes and cannot be
  /// empty.
  ///
  /// Field paths may be used in other contexts to refer to structured fields
  /// defined here. For `map_value`, the field path is represented by a
  /// dot-delimited (`.`) string of segments. Each segment is either a simple
  /// field name (defined below) or a quoted field name. For example, the
  /// structured field `"foo" : { map_value: { "x&y" : { string_value: "hello"
  /// }}}` would be represented by the field path `` foo.`x&y` ``.
  ///
  /// A simple field name contains only characters `a` to `z`, `A` to `Z`,
  /// `0` to `9`, or `_`, and must not start with `0` to `9`. For example,
  /// `foo_bar_17`.
  ///
  /// A quoted field name starts and ends with `` ` `` and
  /// may contain any character. Some characters, including `` ` ``, must be
  /// escaped using a `\`. For example, `` `x&y` `` represents `x&y` and
  /// `` `bak\`tik` `` represents `` bak`tik ``.
  package var fields: Dictionary<String,Google_Firestore_V1_Value> = [:]

  /// Output only. The time at which the document was created.
  ///
  /// This value increases monotonically when a document is deleted then
  /// recreated. It can also be compared to values from other documents and
  /// the `read_time` of a query.
  package var createTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_createTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createTime = newValue}
  }
  /// Returns true if `createTime` has been explicitly set.
  package var hasCreateTime: Bool {self._createTime != nil}
  /// Clears the value of `createTime`. Subsequent reads from it will return its default value.
  package mutating func clearCreateTime() {self._createTime = nil}

  /// Output only. The time at which the document was last changed.
  ///
  /// This value is initially set to the `create_time` then increases
  /// monotonically with each change to the document. It can also be
  /// compared to values from other documents and the `read_time` of a query.
  package var updateTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_updateTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_updateTime = newValue}
  }
  /// Returns true if `updateTime` has been explicitly set.
  package var hasUpdateTime: Bool {self._updateTime != nil}
  /// Clears the value of `updateTime`. Subsequent reads from it will return its default value.
  package mutating func clearUpdateTime() {self._updateTime = nil}

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}

  fileprivate var _createTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _updateTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// A message that can hold any of the supported value types.
package nonisolated struct Google_Firestore_V1_Value: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Must have a value set.
  package var valueType: Google_Firestore_V1_Value.OneOf_ValueType? = nil

  /// A null value.
  package var nullValue: SwiftProtobuf.Google_Protobuf_NullValue {
    get {
      if case .nullValue(let v)? = valueType {return v}
      return .nullValue
    }
    set {valueType = .nullValue(newValue)}
  }

  /// A boolean value.
  package var booleanValue: Bool {
    get {
      if case .booleanValue(let v)? = valueType {return v}
      return false
    }
    set {valueType = .booleanValue(newValue)}
  }

  /// An integer value.
  package var integerValue: Int64 {
    get {
      if case .integerValue(let v)? = valueType {return v}
      return 0
    }
    set {valueType = .integerValue(newValue)}
  }

  /// A double value.
  package var doubleValue: Double {
    get {
      if case .doubleValue(let v)? = valueType {return v}
      return 0
    }
    set {valueType = .doubleValue(newValue)}
  }

  /// A timestamp value.
  ///
  /// Precise only to microseconds. When stored, any additional precision is
  /// rounded down.
  package var timestampValue: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {
      if case .timestampValue(let v)? = valueType {return v}
      return SwiftProtobuf.Google_Protobuf_Timestamp()
    }
    set {valueType = .timestampValue(newValue)}
  }

  /// A string value.
  ///
  /// The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
  /// Only the first 1,500 bytes of the UTF-8 representation are considered by
  /// queries.
  package var stringValue: String {
    get {
      if case .stringValue(let v)? = valueType {return v}
      return String()
    }
    set {valueType = .stringValue(newValue)}
  }

  /// A bytes value.
  ///
  /// Must not exceed 1 MiB - 89 bytes.
  /// Only the first 1,500 bytes are considered by queries.
  package var bytesValue: Data {
    get {
      if case .bytesValue(let v)? = valueType {return v}
      return Data()
    }
    set {valueType = .bytesValue(newValue)}
  }

  /// A reference to a document. For example:
  /// `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
  package var referenceValue: String {
    get {
      if case .referenceValue(let v)? = valueType {return v}
      return String()
    }
    set {valueType = .referenceValue(newValue)}
  }

  /// A geo point value representing a point on the surface of Earth.
  package var geoPointValue: Google_Type_LatLng {
    get {
      if case .geoPointValue(let v)? = valueType {return v}
      return Google_Type_LatLng()
    }
    set {valueType = .geoPointValue(newValue)}
  }

  /// An array value.
  ///
  /// Cannot directly contain another array value, though can contain a
  /// map which contains another array.
  package var arrayValue: Google_Firestore_V1_ArrayValue {
    get {
      if case .arrayValue(let v)? = valueType {return v}
      return Google_Firestore_V1_ArrayValue()
    }
    set {valueType = .arrayValue(newValue)}
  }

  /// A map value.
  package var mapValue: Google_Firestore_V1_MapValue {
    get {
      if case .mapValue(let v)? = valueType {return v}
      return Google_Firestore_V1_MapValue()
    }
    set {valueType = .mapValue(newValue)}
  }

  /// Value which references a field.
  ///
  /// This is considered relative (vs absolute) since it only refers to a field
  /// and not a field within a particular document.
  ///
  /// **Requires:**
  ///
  /// * Must follow [field reference][FieldReference.field_path] limitations.
  ///
  /// * Not allowed to be used when writing documents.
  package var fieldReferenceValue: String {
    get {
      if case .fieldReferenceValue(let v)? = valueType {return v}
      return String()
    }
    set {valueType = .fieldReferenceValue(newValue)}
  }

  /// Pointer to a variable defined elsewhere in a pipeline.
  ///
  /// Unlike `field_reference_value` which references a field within a
  /// document, this refers to a variable, defined in a separate namespace than
  /// the fields of a document.
  package var variableReferenceValue: String {
    get {
      if case .variableReferenceValue(let v)? = valueType {return v}
      return String()
    }
    set {valueType = .variableReferenceValue(newValue)}
  }

  /// A value that represents an unevaluated expression.
  ///
  /// **Requires:**
  ///
  /// * Not allowed to be used when writing documents.
  package var functionValue: Google_Firestore_V1_Function {
    get {
      if case .functionValue(let v)? = valueType {return v}
      return Google_Firestore_V1_Function()
    }
    set {valueType = .functionValue(newValue)}
  }

  /// A value that represents an unevaluated pipeline.
  ///
  /// **Requires:**
  ///
  /// * Not allowed to be used when writing documents.
  package var pipelineValue: Google_Firestore_V1_Pipeline {
    get {
      if case .pipelineValue(let v)? = valueType {return v}
      return Google_Firestore_V1_Pipeline()
    }
    set {valueType = .pipelineValue(newValue)}
  }

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Must have a value set.
  package nonisolated enum OneOf_ValueType: Equatable, Sendable {
    /// A null value.
    case nullValue(SwiftProtobuf.Google_Protobuf_NullValue)
    /// A boolean value.
    case booleanValue(Bool)
    /// An integer value.
    case integerValue(Int64)
    /// A double value.
    case doubleValue(Double)
    /// A timestamp value.
    ///
    /// Precise only to microseconds. When stored, any additional precision is
    /// rounded down.
    case timestampValue(SwiftProtobuf.Google_Protobuf_Timestamp)
    /// A string value.
    ///
    /// The string, represented as UTF-8, must not exceed 1 MiB - 89 bytes.
    /// Only the first 1,500 bytes of the UTF-8 representation are considered by
    /// queries.
    case stringValue(String)
    /// A bytes value.
    ///
    /// Must not exceed 1 MiB - 89 bytes.
    /// Only the first 1,500 bytes are considered by queries.
    case bytesValue(Data)
    /// A reference to a document. For example:
    /// `projects/{project_id}/databases/{database_id}/documents/{document_path}`.
    case referenceValue(String)
    /// A geo point value representing a point on the surface of Earth.
    case geoPointValue(Google_Type_LatLng)
    /// An array value.
    ///
    /// Cannot directly contain another array value, though can contain a
    /// map which contains another array.
    case arrayValue(Google_Firestore_V1_ArrayValue)
    /// A map value.
    case mapValue(Google_Firestore_V1_MapValue)
    /// Value which references a field.
    ///
    /// This is considered relative (vs absolute) since it only refers to a field
    /// and not a field within a particular document.
    ///
    /// **Requires:**
    ///
    /// * Must follow [field reference][FieldReference.field_path] limitations.
    ///
    /// * Not allowed to be used when writing documents.
    case fieldReferenceValue(String)
    /// Pointer to a variable defined elsewhere in a pipeline.
    ///
    /// Unlike `field_reference_value` which references a field within a
    /// document, this refers to a variable, defined in a separate namespace than
    /// the fields of a document.
    case variableReferenceValue(String)
    /// A value that represents an unevaluated expression.
    ///
    /// **Requires:**
    ///
    /// * Not allowed to be used when writing documents.
    case functionValue(Google_Firestore_V1_Function)
    /// A value that represents an unevaluated pipeline.
    ///
    /// **Requires:**
    ///
    /// * Not allowed to be used when writing documents.
    case pipelineValue(Google_Firestore_V1_Pipeline)

  }

  package init() {}
}

/// An array value.
package nonisolated struct Google_Firestore_V1_ArrayValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Values in the array.
  package var values: [Google_Firestore_V1_Value] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// A map value.
package nonisolated struct Google_Firestore_V1_MapValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The map's fields.
  ///
  /// The map keys represent field names. Field names matching the regular
  /// expression `__.*__` are reserved. Reserved field names are forbidden except
  /// in certain documented contexts. The map keys, represented as UTF-8, must
  /// not exceed 1,500 bytes and cannot be empty.
  package var fields: Dictionary<String,Google_Firestore_V1_Value> = [:]

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// Represents an unevaluated scalar expression.
///
/// For example, the expression `like(user_name, "%alice%")` is represented as:
///
/// ```
/// name: "like"
/// args { field_reference: "user_name" }
/// args { string_value: "%alice%" }
/// ```
package nonisolated struct Google_Firestore_V1_Function: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The name of the function to evaluate.
  ///
  /// **Requires:**
  ///
  /// * must be in snake case (lower case with underscore separator).
  package var name: String = String()

  /// Optional. Ordered list of arguments the given function expects.
  package var args: [Google_Firestore_V1_Value] = []

  /// Optional. Optional named arguments that certain functions may support.
  package var options: Dictionary<String,Google_Firestore_V1_Value> = [:]

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  package init() {}
}

/// A Firestore query represented as an ordered list of operations / stages.
package nonisolated struct Google_Firestore_V1_Pipeline: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. Ordered list of stages to evaluate.
  package var stages: [Google_Firestore_V1_Pipeline.Stage] = []

  package var unknownFields = SwiftProtobuf.UnknownStorage()

  /// A single operation within a pipeline.
  ///
  /// A stage is made up of a unique name, and a list of arguments. The exact
  /// number of arguments & types is dependent on the stage type.
  ///
  /// To give an example, the stage `filter(state = "MD")` would be encoded as:
  ///
  /// ```
  /// name: "filter"
  /// args {
  ///   function_value {
  ///     name: "eq"
  ///     args { field_reference_value: "state" }
  ///     args { string_value: "MD" }
  ///   }
  /// }
  /// ```
  ///
  /// See public documentation for the full list.
  package nonisolated struct Stage: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Required. The name of the stage to evaluate.
    ///
    /// **Requires:**
    ///
    /// * must be in snake case (lower case with underscore separator).
    package var name: String = String()

    /// Optional. Ordered list of arguments the given stage expects.
    package var args: [Google_Firestore_V1_Value] = []

    /// Optional. Optional named arguments that certain functions may support.
    package var options: Dictionary<String,Google_Firestore_V1_Value> = [:]

    package var unknownFields = SwiftProtobuf.UnknownStorage()

    package init() {}
  }

  package init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "google.firestore.v1"

nonisolated extension Google_Firestore_V1_Document: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Document"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}fields\0\u{3}create_time\0\u{3}update_time\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Google_Firestore_V1_Value>.self, value: &self.fields) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._createTime) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._updateTime) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.fields.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Google_Firestore_V1_Value>.self, value: self.fields, fieldNumber: 2)
    }
    try { if let v = self._createTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._updateTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_Document, rhs: Google_Firestore_V1_Document) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.fields != rhs.fields {return false}
    if lhs._createTime != rhs._createTime {return false}
    if lhs._updateTime != rhs._updateTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Value"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}boolean_value\0\u{3}integer_value\0\u{3}double_value\0\u{4}\u{2}reference_value\0\u{3}map_value\0\u{4}\u{2}geo_point_value\0\u{3}array_value\0\u{3}timestamp_value\0\u{3}null_value\0\u{4}\u{6}string_value\0\u{3}bytes_value\0\u{3}field_reference_value\0\u{3}function_value\0\u{3}pipeline_value\0\u{3}variable_reference_value\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .booleanValue(v)
        }
      }()
      case 2: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .integerValue(v)
        }
      }()
      case 3: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .doubleValue(v)
        }
      }()
      case 5: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .referenceValue(v)
        }
      }()
      case 6: try {
        var v: Google_Firestore_V1_MapValue?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .mapValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .mapValue(v)
        }
      }()
      case 8: try {
        var v: Google_Type_LatLng?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .geoPointValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .geoPointValue(v)
        }
      }()
      case 9: try {
        var v: Google_Firestore_V1_ArrayValue?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .arrayValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .arrayValue(v)
        }
      }()
      case 10: try {
        var v: SwiftProtobuf.Google_Protobuf_Timestamp?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .timestampValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .timestampValue(v)
        }
      }()
      case 11: try {
        var v: SwiftProtobuf.Google_Protobuf_NullValue?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .nullValue(v)
        }
      }()
      case 17: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .stringValue(v)
        }
      }()
      case 18: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .bytesValue(v)
        }
      }()
      case 19: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .fieldReferenceValue(v)
        }
      }()
      case 20: try {
        var v: Google_Firestore_V1_Function?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .functionValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .functionValue(v)
        }
      }()
      case 21: try {
        var v: Google_Firestore_V1_Pipeline?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .pipelineValue(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .pipelineValue(v)
        }
      }()
      case 22: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .variableReferenceValue(v)
        }
      }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.valueType {
    case .booleanValue?: try {
      guard case .booleanValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .integerValue?: try {
      guard case .integerValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
    }()
    case .doubleValue?: try {
      guard case .doubleValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    }()
    case .referenceValue?: try {
      guard case .referenceValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    }()
    case .mapValue?: try {
      guard case .mapValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .geoPointValue?: try {
      guard case .geoPointValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .arrayValue?: try {
      guard case .arrayValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .timestampValue?: try {
      guard case .timestampValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .nullValue?: try {
      guard case .nullValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 11)
    }()
    case .stringValue?: try {
      guard case .stringValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 17)
    }()
    case .bytesValue?: try {
      guard case .bytesValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 18)
    }()
    case .fieldReferenceValue?: try {
      guard case .fieldReferenceValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 19)
    }()
    case .functionValue?: try {
      guard case .functionValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    }()
    case .pipelineValue?: try {
      guard case .pipelineValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
    }()
    case .variableReferenceValue?: try {
      guard case .variableReferenceValue(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 22)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_Value, rhs: Google_Firestore_V1_Value) -> Bool {
    if lhs.valueType != rhs.valueType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_ArrayValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".ArrayValue"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}values\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_ArrayValue, rhs: Google_Firestore_V1_ArrayValue) -> Bool {
    if lhs.values != rhs.values {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_MapValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".MapValue"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fields\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Google_Firestore_V1_Value>.self, value: &self.fields) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fields.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Google_Firestore_V1_Value>.self, value: self.fields, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_MapValue, rhs: Google_Firestore_V1_MapValue) -> Bool {
    if lhs.fields != rhs.fields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_Function: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Function"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}args\0\u{1}options\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.args) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Google_Firestore_V1_Value>.self, value: &self.options) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.args.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.args, fieldNumber: 2)
    }
    if !self.options.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Google_Firestore_V1_Value>.self, value: self.options, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_Function, rhs: Google_Firestore_V1_Function) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.args != rhs.args {return false}
    if lhs.options != rhs.options {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_Pipeline: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = _protobuf_package + ".Pipeline"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}stages\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.stages) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.stages.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.stages, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_Pipeline, rhs: Google_Firestore_V1_Pipeline) -> Bool {
    if lhs.stages != rhs.stages {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Google_Firestore_V1_Pipeline.Stage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  package static let protoMessageName: String = Google_Firestore_V1_Pipeline.protoMessageName + ".Stage"
  package static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}args\0\u{1}options\0")

  package mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.args) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Google_Firestore_V1_Value>.self, value: &self.options) }()
      default: break
      }
    }
  }

  package func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.args.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.args, fieldNumber: 2)
    }
    if !self.options.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Google_Firestore_V1_Value>.self, value: self.options, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  package static func ==(lhs: Google_Firestore_V1_Pipeline.Stage, rhs: Google_Firestore_V1_Pipeline.Stage) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.args != rhs.args {return false}
    if lhs.options != rhs.options {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
